#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

git diff -U0 --no-color $against | python3 /usr/local/Cellar/clang-format/10.0.1/share/clang/clang-format-diff.py -i -p1 -binary="/usr/local/bin/clang-format"
if (( $? )); then
  echo "Fail to format:" >&2
  exit 1
else
  echo "Formatted successful"

  # Stage changed and already staged files again to be able to commit changes made by clang-format-diff.py
  git update-index --again
fi

# Regexp for grep to only choose some file extensions for formatting
exts="\.\(cpp\|h\|hpp\|cc\|mm\|c\|hxx\|hh\|cxx\|md\|txt\|cmake\|py\|yml\)$"

# Loop over staged files that has been added modified or changed its type
for file in `git diff --cached --name-only --diff-filter=AMT | grep $exts`
do
  # remove trailing whitespaces(as result it can add extra new lines at the end of the file)
  sed -E -i ''  's/[[:space:]]*$//' $file

  # remove trailing new lines
  printf %s "$(< "$file")" > "$file"
done

# Stage changed and already staged files again to be able to commit changes made by clang-format-diff.py
git update-index --again

# We will not commit if after clang-format-diff.py diff is empty
diffstat=$(git diff --staged --stat)
if [ -z "${diffstat}" ]; then
  echo "Commits with empty diff are not allowed"
  git reset
  exit 1
fi

# If you want to allow non-ASCII filenames set this variable to true.
allownonascii=$(git config --bool hooks.allownonascii)

# Redirect output to stderr.
exec 1>&2

# Cross platform projects tend to avoid non-ASCII filenames; prevent
# them from being added to the repository. We exploit the fact that the
# printable range starts at the space character and ends with tilde.
if [ "$allownonascii" != "true" ] &&
	# Note that the use of brackets around a tr range is ok here, (it's
	# even required, for portability to Solaris 10's /usr/bin/tr), since
	# the square bracket bytes happen to fall in the designated range.
	test $(git diff --cached --name-only --diff-filter=AR -z $against |
	  LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
then
	cat <<\EOF
Error: Attempt to add a non-ASCII file name.

This can cause problems if you want to work with people on other platforms.

To be portable it is advisable to rename the file.

If you know what you are doing you can disable this check using:

  git config hooks.allownonascii true
EOF
	exit 1
fi

# If there are whitespace errors, print the offending file names and fail.
#exec git diff-index --check --cached $against --
